/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_martian_util_JniTestUtil */

#ifndef _Included_com_example_martian_util_JniTestUtil
#define _Included_com_example_martian_util_JniTestUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_martian_util_JniTestUtil
 * Method:    getNativeData
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_martian_util_JniTestUtil_getNativeData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
